package dao; import java.sql.*; import model.Patient; import util.db;
public class PatientDAO {
    private void print(ResultSet rs)throws Exception{System.out.println(rs.getInt("id")+" | "+rs.getString("name")+" | "+rs.getString("email")+" | "+rs.getString("disease")+" | "+rs.getString("doctor")+" | Rs."+rs.getDouble("fees")+" | "+rs.getString("admit_date"));}
    public boolean add(Patient p){try{PreparedStatement ps=db.getConnection().prepareStatement("INSERT INTO patients(name,email,disease,doctor,fees,admit_date)VALUES(?,?,?,?,?,?)");ps.setString(1,p.getName());ps.setString(2,p.getEmail());ps.setString(3,p.getDisease());ps.setString(4,p.getDoctor());ps.setDouble(5,p.getFees());ps.setString(6,p.getAdmitDate());return ps.executeUpdate()>0;}catch(Exception e){return false;}}
    public void viewAll(){try{ResultSet rs=db.getConnection().prepareStatement("SELECT * FROM patients").executeQuery();boolean f=false;while(rs.next()){f=true;print(rs);}if(!f)System.out.println("No patients.");}catch(Exception e){}}
    public void searchById(int id){try{PreparedStatement ps=db.getConnection().prepareStatement("SELECT * FROM patients WHERE id=?");ps.setInt(1,id);ResultSet rs=ps.executeQuery();if(rs.next())print(rs);else System.out.println("Not found.");}catch(Exception e){}}
    public void searchByDoctor(String doc){try{PreparedStatement ps=db.getConnection().prepareStatement("SELECT * FROM patients WHERE doctor=?");ps.setString(1,doc);ResultSet rs=ps.executeQuery();boolean f=false;while(rs.next()){f=true;print(rs);}if(!f)System.out.println("None.");}catch(Exception e){}}
    public boolean updateFees(int id,double fees){try{PreparedStatement ps=db.getConnection().prepareStatement("UPDATE patients SET fees=? WHERE id=?");ps.setDouble(1,fees);ps.setInt(2,id);return ps.executeUpdate()>0;}catch(Exception e){return false;}}
    public boolean delete(int id){try{PreparedStatement ps=db.getConnection().prepareStatement("DELETE FROM patients WHERE id=?");ps.setInt(1,id);return ps.executeUpdate()>0;}catch(Exception e){return false;}}
    public void count(){try{ResultSet rs=db.getConnection().prepareStatement("SELECT COUNT(*) FROM patients").executeQuery();if(rs.next())System.out.println("Total Patients: "+rs.getInt(1));}catch(Exception e){}}
    public void highestFees(){try{ResultSet rs=db.getConnection().prepareStatement("SELECT * FROM patients ORDER BY fees DESC LIMIT 1").executeQuery();if(rs.next()){System.out.println("Highest Fees:");print(rs);}}catch(Exception e){}}
    public void sortByFees(){try{ResultSet rs=db.getConnection().prepareStatement("SELECT * FROM patients ORDER BY fees DESC").executeQuery();while(rs.next())print(rs);}catch(Exception e){}}
    public void diseaseReport(){try{ResultSet rs=db.getConnection().prepareStatement("SELECT disease,COUNT(*) as cnt FROM patients GROUP BY disease").executeQuery();System.out.println("Disease | Count");while(rs.next())System.out.println(rs.getString("disease")+" | "+rs.getInt("cnt"));}catch(Exception e){}}
}
